#!/usr/bin/env bash
# Configure host resolution as required

# Replace localhost entry
sudo sed -i 's/127.0.0.1\s\+localhost/127.0.0.2\tlocalhost/' /etc/hosts

# Add or replace facebook.com entry
grep -q "facebook.com" /etc/hosts
if [ $? -eq 0 ]; then
    sudo sed -i 's/.*facebook.com/8.8.8.8\tfacebook.com/' /etc/hosts
else
    echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
fi
