#!/usr/bin/env bash
# Configure host resolution as required
sudo sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts
sudo sed -i '/facebook.com/d' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
